import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  dynamic
}: Readonly<{
  children: React.ReactNode;
  dynamic: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="importmap"
          dangerouslySetInnerHTML={{
            __html: `
{
  "imports": {
    "react": "https://esm.sh/react",
    "react-dom": "https://esm.sh/react-dom",
  }
}
      `,
          }}
        />
      </head>
      <body className={inter.className}>
        {children}
        {dynamic}
      </body>
    </html>
  );
}
